# Generated by Django 4.1 on 2023-11-19 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commublog', '0019_alter_comment_created_date_alter_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 14, 30, 31, 307931, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 14, 30, 31, 307591, tzinfo=datetime.timezone.utc)),
        ),
    ]
